# Generated by Django 3.2.6 on 2021-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
