# Generated by Django 3.2.6 on 2021-09-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0069_offer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
