# Generated by Django 3.2.6 on 2021-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0070_auto_20210901_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
