# Generated by Django 3.2.6 on 2021-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0074_auto_20210904_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpostrequest',
            name='post_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESERVED', 'RESERVED'), ('DELETE', 'DELETE')], default='ACTIVE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='recently_viewed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='supported_formats',
            field=models.ManyToManyField(blank=True, to='mainApp.FileFormats'),
        ),
    ]
