# Generated by Django 3.2.6 on 2021-09-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0076_buyerpostrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerpostrequest',
            old_name='deliver_time',
            new_name='delivery_time',
        ),
    ]
