# Generated by Django 3.2.6 on 2021-09-05 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0077_rename_deliver_time_buyerpostrequest_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='recently_viewed',
        ),
        migrations.CreateModel(
            name='SendOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_offer_slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('offer_letter', models.TextField(null=True)),
                ('offered_price', models.PositiveIntegerField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_post_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_post_request', to='mainApp.buyerpostrequest')),
                ('delivery_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_delivery_time', to='mainApp.deliverytime')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
