# Generated by Django 3.2.6 on 2021-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0079_auto_20210904_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
