# Generated by Django 3.2.6 on 2021-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0080_selleraccount_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
