# Generated by Django 3.2.6 on 2021-09-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0082_auto_20210906_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='method',
            field=models.CharField(choices=[('PAYPAL', 'PAYPAL'), ('SSLCOMMERZ', 'SSLCOMERZ')], max_length=220, null=True),
        ),
    ]
