# Generated by Django 3.2.6 on 2021-09-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0083_withdrawmodel_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
