# Generated by Django 3.2.6 on 2021-09-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0084_alter_withdrawmodel_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDrawPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=220, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='withdrawmodel',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.withdrawpaymentmethod'),
        ),
    ]
