# Generated by Django 3.2.6 on 2021-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0085_auto_20210906_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='withdrawmodel',
            name='on_review',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
