# Generated by Django 3.2.6 on 2021-09-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0086_auto_20210907_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpostrequest',
            name='post_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESERVED', 'RESERVED')], default='ACTIVE', max_length=100, null=True),
        ),
    ]
