# Generated by Django 3.2.6 on 2021-09-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0090_offer_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
